apiVersion: v1
kind: Secret
metadata:
  name: finnexus-backend-secrets
  namespace: finnexus-production
  labels:
    app: finnexus-backend
    version: v1.0.0
    component: backend
    tier: application
    environment: production
type: Opaque
data:
  # Database URLs (base64 encoded)
  DATABASE_URL: cG9zdGdyZXNxbDovL2Zpbm5leHVzOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9maW5fbmV4dXNfYWk=
  MONGO_URI: bW9uZ29kYjovL2Zpbm5leHVzOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9maW5uZXh1c2Fp
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  
  # JWT and encryption keys (base64 encoded)
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1oZXJl
  ENCRYPTION_KEY: eW91ci1lbmNyeXB0aW9uLWtleS1oZXJl
  API_KEY_SECRET: eW91ci1hcGkta2V5LXNlY3JldC1oZXJl
  
  # SSL certificates (base64 encoded)
  SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  SSL_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  
  # External service credentials
  PAYMENT_GATEWAY_API_KEY: eW91ci1wYXltZW50LWdhdGV3YXktYXBpLWtleQ==
  EMAIL_SERVICE_API_KEY: eW91ci1lbWFpbC1zZXJ2aWNlLWFwaS1rZXk=
  SMS_SERVICE_API_KEY: eW91ci1zbXMtc2VydmljZS1hcGkta2V5
  BLOCKCHAIN_RPC_URL: aHR0cHM6Ly9tYWlubmV0LmluZnVyYS5hbGlhbmNlLmV0aGVyZXVtLm5vZGVpbmZyYS5pby92MS95b3VyLXByb2plY3QtaWQ=
  
  # Monitoring credentials
  PROMETHEUS_USERNAME: cHJvbWV0aGV1cw==
  PROMETHEUS_PASSWORD: cHJvbWV0aGV1cy1wYXNzd29yZA==
  GRAFANA_USERNAME: YWRtaW4=
  GRAFANA_PASSWORD: YWRtaW4tcGFzc3dvcmQ=
  JAEGER_USERNAME: amFlZ2Vy
  JAEGER_PASSWORD: amFlZ2VyLXBhc3N3b3Jk
  
  # Logging credentials
  ELASTICSEARCH_USERNAME:IGVsYXN0aWNzZWFyY2g=
  ELASTICSEARCH_PASSWORD:IGVsYXN0aWNzZWFyY2gtcGFzc3dvcmQ=
  KIBANA_USERNAME: a2liYW5h
  KIBANA_PASSWORD: a2liYW5hLXBhc3N3b3Jk
  
  # Backup credentials
  AWS_ACCESS_KEY_ID: eW91ci1hd3MtYWNjZXNzLWtleS1pZA==
  AWS_SECRET_ACCESS_KEY: eW91ci1hd3Mtc2VjcmV0LWFjY2Vzcy1rZXk=
  AWS_REGION: dXMtZWFzdC0x
  S3_BUCKET_NAME:IGZpbm5leHVzLWJhY2t1cHM=
  
  # Alerting credentials
  PAGERDUTY_INTEGRATION_KEY: eW91ci1wYWdlcmR1dHktaW50ZWdyYXRpb24ta2V5
  OPSGENIE_API_KEY: eW91ci1vcHMnZ2VuaWUtYXBpLWtleQ==
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMveW91ci13ZWJob29rLXVybA==
  
  # Compliance and security
  ENCRYPTION_ALGORITHM:QUVTLTI1Ni1HQ00=
  HASH_ALGORITHM:U0hBMjU2
  TOKEN_EXPIRY:MzYwMA==
  REFRESH_TOKEN_EXPIRY:ODY0MDA=
  SESSION_TIMEOUT:MTgwMA==
  MAX_LOGIN_ATTEMPTS:1
  LOCKOUT_DURATION:OTAw
  PASSWORD_MIN_LENGTH:MTI=
  PASSWORD_REQUIRE_UPPERCASE: dHJ1ZQ==
  PASSWORD_REQUIRE_LOWERCASE: dHJ1ZQ==
  PASSWORD_REQUIRE_NUMBERS: dHJ1ZQ==
  PASSWORD_REQUIRE_SYMBOLS: dHJ1ZQ==
  
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: IDYwMDAw
  RATE_LIMIT_MAX_REQUESTS: MTAw
  RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS: dHJ1ZQ==
  RATE_LIMIT_SKIP_FAILED_REQUESTS:IGZhbHNl
  RATE_LIMIT_KEY_GENERATOR:IGlw
  RATE_LIMIT_HEADER_NAME: IFgtUmF0ZS1MaW1pdC1BZnRlcg==
  RATE_LIMIT_MESSAGE:IFJhdGUgbGltaXQgZXhjZWVkZWQsIHBsZWFzZSB0cnkgYWdhaW4gbGF0ZXIu
  RATE_LIMIT_STATUS_CODE:IDQyOQ==
  
  # Database configuration
  DB_POOL_SIZE: IDIw
  DB_POOL_IDLE_TIMEOUT:IDMwMDAw
  DB_POOL_CONNECTION_TIMEOUT: MTAwMDA=
  DB_POOL_ACQUIRE_TIMEOUT: IDYwMDAw
  DB_POOL_CREATE_TIMEOUT: IDMwMDAw
  DB_POOL_DESTROY_TIMEOUT: IDUwMDA=
  DB_POOL_REAP_INTERVAL: IDMwMDAw
  DB_POOL_CREATE_RETRY_INTERVAL: IDIwMA==
  DB_POOL_PROPAGATE_CREATE_ERROR:IGZhbHNl
  
  # Cache configuration
  CACHE_TTL: IDM2MDA=
  CACHE_MAX_SIZE:IDEwMDA=
  CACHE_UPDATE_FREQUENCY:IDYw
  CACHE_CLEANUP_INTERVAL: IDM2MDA=
  CACHE_EVICTION_POLICY:IGxydQ==
  
  # Monitoring configuration
  METRICS_COLLECTION_INTERVAL:IDMw
  METRICS_RETENTION_PERIOD:IDMwZA==
  METRICS_AGGREGATION_INTERVAL:IDU=
  METRICS_ALERT_THRESHOLD:IDAuOA==
  METRICS_WARNING_THRESHOLD:IDAuNg==
  METRICS_CRITICAL_THRESHOLD:IDAuOQ==
  
  # Logging configuration
  LOG_LEVEL:IGluZm8=
  LOG_FORMAT:IGpzb24=
  LOG_MAX_SIZE:IDEwTQ==
  LOG_MAX_FILES:IDU=
  LOG_MAX_AGE:IDMwZA==
  LOG_COMPRESS: dHJ1ZQ==
  LOG_LOCAL_TIME:IGZhbHNl
  
  # Security configuration
  ENABLE_CSRF_PROTECTION: dHJ1ZQ==
  ENABLE_XSS_PROTECTION: dHJ1ZQ==
  ENABLE_CONTENT_TYPE_VALIDATION: dHJ1ZQ==
  ENABLE_REQUEST_SIZE_LIMIT: dHJ1ZQ==
  ENABLE_RESPONSE_SIZE_LIMIT: dHJ1ZQ==
  ENABLE_REQUEST_TIMEOUT: dHJ1ZQ==
  ENABLE_RESPONSE_TIMEOUT: dHJ1ZQ==
  ENABLE_CONNECTION_LIMIT: dHJ1ZQ==
  ENABLE_MEMORY_LIMIT: dHJ1ZQ==
  ENABLE_CPU_LIMIT: dHJ1ZQ==
  ENABLE_DISK_LIMIT: dHJ1ZQ==
  ENABLE_NETWORK_LIMIT: dHJ1ZQ==
