version: '3.8'
services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - finai-network
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres:5432/finainexus
      - X_API_KEY=
    depends_on:
      - postgres
    networks:
      - finai-network
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finainexus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finai-network
networks:
  finai-network:
    driver: bridge
volumes:
  postgres-data:
