# Docker Compose for full monorepo (backend + frontend)
version: '3.8'
services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: unless-stopped
  frontend:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
