# Docker Compose for full monorepo (backend + frontend)
version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - apps/web/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
