version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: finainexus_prod
      POSTGRES_USER: finainexus
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./apps/backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://finainexus:${DB_PASSWORD}@postgres:5432/finainexus_prod
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build: ./apps/frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: