apiVersion: v1
kind: ServiceAccount
metadata:
  name: finnexus-backend-sa
  namespace: finnexus-ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: finnexus-frontend-sa
  namespace: finnexus-ai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finnexus-ai
  name: finnexus-backend-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: finnexus-backend-binding
  namespace: finnexus-ai
subjects:
- kind: ServiceAccount
  name: finnexus-backend-sa
  namespace: finnexus-ai
roleRef:
  kind: Role
  name: finnexus-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finnexus-ai
  name: finnexus-frontend-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: finnexus-frontend-binding
  namespace: finnexus-ai
subjects:
- kind: ServiceAccount
  name: finnexus-frontend-sa
  namespace: finnexus-ai
roleRef:
  kind: Role
  name: finnexus-frontend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: finnexus-network-policy
  namespace: finnexus-ai
spec:
  podSelector:
    matchLabels:
      app: finnexus-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: finnexus-ingress
    ports:
    - protocol: TCP
      port: 5000
  - from:
    - namespaceSelector:
        matchLabels:
          name: finnexus-monitoring
    ports:
    - protocol: TCP
      port: 5000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: finnexus-ai
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: finnexus-frontend-network-policy
  namespace: finnexus-ai
spec:
  podSelector:
    matchLabels:
      app: finnexus-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: finnexus-ingress
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: finnexus-ai
    ports:
    - protocol: TCP
      port: 80
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
