apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finnexus-backend.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "finnexus-backend.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "finnexus-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "finnexus-backend.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "finnexus-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.app.environment | quote }}
        - name: PORT
          value: "3000"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=1536 --max-semi-space-size=128"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- with .Values.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.secrets.enabled }}
        envFrom:
        - secretRef:
            name: {{ include "finnexus-backend.secretName" . }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        - configMapRef:
            name: {{ include "finnexus-backend.configMapName" . }}
        {{- end }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
        - name: tmp
          mountPath: /tmp
        {{- if .Values.volumes.ssl.enabled }}
        - name: ssl-certs
          mountPath: /app/ssl
          readOnly: true
        {{- end }}
        {{- if .Values.configMap.enabled }}
        - name: config
          mountPath: /app/config
          readOnly: true
        {{- end }}
        {{- with .Values.deployment.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.deployment.containerSecurityContext | nindent 10 }}
        {{- with .Values.deployment.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: logs
        emptyDir:
          sizeLimit: {{ .Values.volumes.logs.size }}
      - name: uploads
        emptyDir:
          sizeLimit: {{ .Values.volumes.uploads.size }}
      - name: tmp
        emptyDir:
          sizeLimit: {{ .Values.volumes.tmp.size }}
      {{- if .Values.volumes.ssl.enabled }}
      - name: ssl-certs
        secret:
          secretName: {{ .Values.volumes.ssl.secretName }}
      {{- end }}
      {{- if .Values.configMap.enabled }}
      - name: config
        configMap:
          name: {{ include "finnexus-backend.configMapName" . }}
      {{- end }}
      {{- with .Values.deployment.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.deployment.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.deployment.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
