apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: finainexus
spec:
  selector:
    matchLabels: { app: postgres }
  replicas: 1
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: finai-secrets
                key: db-password
          - name: POSTGRES_DB
            value: "finainexus"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: finainexus
spec:
  ports:
    - port: 5432
  selector:
    app: postgres