apiVersion: batch/v1
kind: CronJob
metadata:
  name: finainexus-backup
  namespace: finainexus
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:14
            command:
            - /bin/bash
            - -c
            - |
              pg_dump -h postgres-service -U finainexus -d finainexus_prod > /backup/backup_$(date +%Y%m%d_%H%M%S).sql
              aws s3 cp /backup/backup_$(date +%Y%m%d_%H%M%S).sql s3://finainexus-backups/
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: finainexus-secrets
                  key: db-password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
