apiVersion: v1
kind: ServiceAccount
metadata:
  name: finainexus-backup-sa
  namespace: finainexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: finainexus-backup-role
  namespace: finainexus
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: finainexus-backup-rolebinding
  namespace: finainexus
subjects:
- kind: ServiceAccount
  name: finainexus-backup-sa
  namespace: finainexus
roleRef:
  kind: Role
  name: finainexus-backup-role
  apiGroup: rbac.authorization.k8s.io