apiVersion: apps/v1
kind: Deployment
metadata:
  name: finainexus-backend
  namespace: finainexus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finainexus-backend
  template:
    metadata:
      labels:
        app: finainexus-backend
    spec:
      containers:
      - name: backend
        image: finainexus/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: finainexus-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: finainexus-secrets
              key: redis-url
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5