apiVersion: v1
kind: Namespace
metadata:
  name: finnexusai-production
  labels:
    name: finnexusai-production
    environment: production
    tier: production
  annotations:
    description: "FinNexusAI Production Environment"
    contact: "devops@finnexusai.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: finnexusai-production-quota
  namespace: finnexusai-production
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    requests.storage: 500Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: finnexusai-production-limits
  namespace: finnexusai-production
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim

