# FinNexusAI Prometheus Configuration
# Comprehensive monitoring for production trading platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'finnexusai-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FinNexusAI Backend Services
  - job_name: 'finnexusai-backend'
    static_configs:
      - targets: 
        - 'backend-1:3000'
        - 'backend-2:3000'
        - 'backend-3:3000'
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter-1:9100'
        - 'node-exporter-2:9100'
        - 'node-exporter-3:9100'
    scrape_interval: 15s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - 'cadvisor:8080'
    scrape_interval: 15s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: 
        - 'postgres-exporter:9187'
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: 
        - 'redis-exporter:9121'
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: 
        - 'nginx-exporter:9113'
    scrape_interval: 30s

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Trading Engine Metrics
  - job_name: 'trading-engine'
    static_configs:
      - targets: 
        - 'trading-engine:8080'
    metrics_path: '/metrics'
    scrape_interval: 1s  # High frequency for trading metrics
    scrape_timeout: 500ms

  # HFT Engine Metrics
  - job_name: 'hft-engine'
    static_configs:
      - targets: 
        - 'hft-engine:8081'
    metrics_path: '/metrics'
    scrape_interval: 100ms  # Ultra-high frequency for HFT
    scrape_timeout: 50ms

  # Arbitrage Engine Metrics
  - job_name: 'arbitrage-engine'
    static_configs:
      - targets: 
        - 'arbitrage-engine:8082'
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Options & Derivatives Engine
  - job_name: 'derivatives-engine'
    static_configs:
      - targets: 
        - 'derivatives-engine:8083'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Futurist Sandbox Engine
  - job_name: 'sandbox-engine'
    static_configs:
      - targets: 
        - 'sandbox-engine:8084'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # AI Services
  - job_name: 'ai-services'
    static_configs:
      - targets: 
        - 'ai-price-prediction:8085'
        - 'ai-sentiment-analysis:8086'
        - 'ai-portfolio-optimization:8087'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Security Services
  - job_name: 'security-services'
    static_configs:
      - targets: 
        - 'security-monitoring:8088'
        - 'threat-detection:8089'
        - 'audit-service:8090'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Payment Processing
  - job_name: 'payment-services'
    static_configs:
      - targets: 
        - 'payment-processor:8091'
        - 'stripe-webhook:8092'
        - 'coinbase-webhook:8093'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Blockchain Services
  - job_name: 'blockchain-services'
    static_configs:
      - targets: 
        - 'ethereum-node:8094'
        - 'polygon-node:8095'
        - 'bsc-node:8096'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # External API Health Checks
  - job_name: 'external-apis'
    static_configs:
      - targets: 
        - 'coingecko-health:8097'
        - 'alpha-vantage-health:8098'
        - 'bloomberg-health:8099'
    metrics_path: '/health'
    scrape_interval: 60s

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.finnexusai.com/api/v1/write"
    basic_auth:
      username: "prometheus"
      password: "${PROMETHEUS_REMOTE_WRITE_PASSWORD}"
    queue_config:
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      max_retries: 10
      min_backoff: 30ms
      max_backoff: 100ms

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 100GB
    wal-compression: true

