name: FinNexusAI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup PowerShell logging module
      - name: Setup Logging Module
        shell: pwsh
        run: |
          Import-Module "$PWD\modules\logging\logging.psm1" -Force
          Initialize-Log
          Write-Log -Message "GitHub Actions workflow started" -Level INFO

      # Run your main tasks with logging
      - name: Run tasks.ps1
        shell: pwsh
        run: |
          try {
            Import-Module "$PWD\modules\logging\logging.psm1" -Force
            Initialize-Log
            Write-Log -Message "Executing tasks.ps1 in CI pipeline" -Level INFO
            ./tasks.ps1
          } catch {
            Write-Log -Message "CI pipeline failed: $_" -Level ERROR
            exit 1
          }

      # Tail last 50 log lines directly in Actions UI for debugging
      - name: Tail last 50 log lines
        if: always()
        shell: pwsh
        run: |
          $logDir = "$env:USERPROFILE\FinAI_Logs"
          if (Test-Path $logDir) {
            $latest = Get-ChildItem -Path $logDir -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
            if ($latest) {
              Write-Host "=== Showing last 50 lines of log: $($latest.Name) ==="
              Get-Content -Path $latest.FullName -Tail 50
            } else {
              Write-Host "⚠️ No log files found."
            }
          } else {
            Write-Host "⚠️ Log directory not found."
          }

      # Upload full logs as artifact (optional, for full audit trail)
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: finai-logs
          path: ${{ env.USERPROFILE }}\FinAI_Logs
